+incdir+../common/rtl
../common/rtl/wasp1_pkg.sv
../common/rtl/debug_if.sv
rtl/core_types_pkg.sv
rtl/core_alu.sv
rtl/core_branch.sv
rtl/core_lsu.sv
rtl/core_csr.sv
rtl/core_trap.sv
rtl/core_hazard.sv
rtl/core_regfile.sv
rtl/core_decode.sv
rtl/core_wb.sv
rtl/core_debug_ctrl.sv
rtl/core_pipe.sv
rtl/core_int_datapath.sv
tb/tb_core_int_datapath.sv
