+incdir+../common/rtl
../common/rtl/wasp1_pkg.sv
rtl/core_types_pkg.sv
rtl/core_alu.sv
rtl/core_regfile.sv
rtl/core_decode.sv
rtl/core_wb.sv
rtl/core_pipe.sv
rtl/core_int_datapath.sv
tb/tb_core_int_datapath.sv
