#!/usr/bin/env python3
"""Add an explicit white page behind KiCad schematic SVG exports.

KiCad 10 exports schematic SVGs with a transparent canvas. Some macOS PDF and
Quick Look paths composite alternating hierarchy pages against black, which
makes otherwise-correct drawings unusable as review collateral. This helper
adds only a page-sized background rectangle; it does not alter schematic
geometry or electrical content.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re


BACKGROUND_MARKER = 'id="wasp1-page-background"'


def add_background(path: Path) -> None:
    """Insert one white view-box-sized rectangle after the SVG description."""
    text = path.read_text(encoding="utf-8")
    if BACKGROUND_MARKER in text:
        return

    match = re.search(
        r'viewBox="([\d.]+) ([\d.]+) ([\d.]+) ([\d.]+)"', text
    )
    if not match:
        raise ValueError(f"{path}: SVG viewBox is missing")
    x, y, width, height = match.groups()
    background = (
        f'<rect id="wasp1-page-background" x="{x}" y="{y}" '
        f'width="{width}" height="{height}" fill="#ffffff" />\n'
    )
    anchor = "  <desc>Image generated by Eeschema-SVG </desc>\n"
    if anchor not in text:
        raise ValueError(f"{path}: KiCad SVG description anchor is missing")
    path.write_text(text.replace(anchor, anchor + background, 1), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("paths", nargs="+", type=Path)
    args = parser.parse_args()
    for path in args.paths:
        add_background(path)
        print(f"PASS white SVG background {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
