`timescale 1ns/1ps
`include "wasp1_target_defs.svh"

// wasp1 single-core SoC top.
//
// This first top-level integration wires the verified tile, AHB-Lite fabric,
// DMA master/control block, executable OTP, I-SRAM, D-SRAM, WDG, timer, INTC,
// UART, I2C, and GPIO. The bus-visible topology is two masters
// (core-side bridge and DMA) and ten decoded external slave windows including
// the DMA control register window.
module wasp1 #(
  parameter int GPIO_WIDTH = 32,          // Number of GPIO pins.
  parameter int ISRAM_BYTES = wasp1_pkg::ISRAM_SIZE,
  parameter int DSRAM_BYTES = wasp1_pkg::DSRAM_SIZE,
  parameter int OTP_BYTES = wasp1_pkg::OTP_SIZE
) (
  input  logic                  hclk_i,          // SoC clock for all integrated logic.
  input  logic                  hresetn_i,       // Active-low asynchronous SoC reset.
  input  logic                  uart_rx_i,       // UART receive pin.
  output logic                  uart_tx_o,       // UART transmit pin.
  input  logic                  i2c_scl_i,       // Observed I2C SCL level.
  input  logic                  i2c_sda_i,       // Observed I2C SDA level.
  output logic                  i2c_scl_o,       // I2C SCL low-drive value.
  output logic                  i2c_scl_oe_o,    // I2C SCL low-drive enable.
  output logic                  i2c_sda_o,       // I2C SDA low-drive value.
  output logic                  i2c_sda_oe_o,    // I2C SDA low-drive enable.
  input  logic [GPIO_WIDTH-1:0] gpio_in_i,       // GPIO sampled input pins.
  output logic [GPIO_WIDTH-1:0] gpio_out_o,      // GPIO output data pins.
  output logic [GPIO_WIDTH-1:0] gpio_oe_o,       // GPIO output enables.
  output logic                  wdg_reset_req_o, // Watchdog-requested system reset pulse/level.
  output logic                  trap_valid_o,    // Observable core trap event.
  output logic [4:0]            trap_cause_o,    // Observable core trap cause.
  output logic                  bus_grant_idx_o, // Current AHB fabric grant: 0 core, 1 DMA.
  input  logic                  jtag_tck_i,      // JTAG test clock for the integrated Debug Module.
  input  logic                  jtag_trst_ni,    // Active-low JTAG TAP reset.
  input  logic                  jtag_tms_i,      // JTAG test mode select.
  input  logic                  jtag_tdi_i,      // JTAG serial data input.
  output logic                  jtag_tdo_o,      // JTAG serial data output.
  output logic                  dbg_halted_o,    // Core halted status to external debug logic.
  output logic                  dbg_running_o,   // Core running status to external debug logic.
  output logic                  dbg_dmactive_o,  // Debug Module active state.
  output logic                  dbg_ndmreset_o,  // Debug Module non-debug reset request.
  output logic                  dbg_dtm_hardreset_o // DTMCS.dmihardreset pulse.
);
  import wasp1_pkg::*;

  localparam int EXT_SLAVE_COUNT = AHB_SLAVE_DEFAULT;

  // Tile downstream memory ports before conversion to the core AHB master.
  mem_req_rsp_if imem_if (
    .clk(hclk_i),
    .rst_n(hresetn_i)
  );

  mem_req_rsp_if dmem_if (
    .clk(hclk_i),
    .rst_n(hresetn_i)
  );

  // Internal structured debug channel. Discrete top-level ports keep this SoC
  // wrapper usable as a concrete lint and synthesis top.
  debug_if core_debug (
    .clk(hclk_i),
    .rst_n(hresetn_i)
  );

  // Core-side AHB master generated by the I/D memory bridge.
  logic [ADDR_WIDTH-1:0] core_haddr;
  logic [1:0]            core_htrans;
  logic                  core_hwrite;
  logic [2:0]            core_hsize;
  logic [2:0]            core_hburst;
  logic [3:0]            core_hprot;
  logic                  core_hmastlock;
  logic [DATA_WIDTH-1:0] core_hwdata;
  logic [DATA_WIDTH-1:0] core_hrdata;
  logic                  core_hready;
  logic                  core_hresp;

  // DMA AHB master signals.
  logic [ADDR_WIDTH-1:0] dma_m_haddr;
  logic [1:0]            dma_m_htrans;
  logic                  dma_m_hwrite;
  logic [2:0]            dma_m_hsize;
  logic [2:0]            dma_m_hburst;
  logic [3:0]            dma_m_hprot;
  logic                  dma_m_hmastlock;
  logic [DATA_WIDTH-1:0] dma_m_hwdata;
  logic [DATA_WIDTH-1:0] dma_m_hrdata;
  logic                  dma_m_hready;
  logic                  dma_m_hresp;

  // Shared AHB slave-side bus after arbitration and address decode.
  logic [EXT_SLAVE_COUNT-1:0]                  slave_hsel;
  logic [ADDR_WIDTH-1:0]                       slave_haddr;
  logic [1:0]                                  slave_htrans;
  logic                                        slave_hwrite;
  logic [2:0]                                  slave_hsize;
  logic [2:0]                                  slave_hburst;
  logic [3:0]                                  slave_hprot;
  logic                                        slave_hmastlock;
  logic [DATA_WIDTH-1:0]                       slave_hwdata;
  logic [EXT_SLAVE_COUNT-1:0][DATA_WIDTH-1:0] slave_hrdata;
  logic [EXT_SLAVE_COUNT-1:0]                  slave_hready;
  logic [EXT_SLAVE_COUNT-1:0]                  slave_hresp;

  // Peripheral interrupt sources and INTC outputs.
  logic [IRQ_SRC_COUNT-1:0] irq_src;
  logic                    timer_irq;
  logic                    wdg_irq;
  logic                    uart_irq;
  logic                    i2c_irq;
  logic                    gpio_irq;
  logic                    dma_irq;
  logic                    external_irq;
  logic [$clog2(IRQ_SRC_COUNT)-1:0] intc_claim_id;

  // Core/tile observation signals retained for debug and top-level tests.
  logic        commit_valid;
  logic [4:0]  commit_rd;
  logic [31:0] commit_data;
  logic        ex_valid;
  logic [31:0] ex_pc;
  logic [31:0] ex_instr;
  logic        illegal;
  logic        lsu_fault;
  logic        trap_interrupt;
  logic [31:0] trap_tval;
  logic [31:0] trap_pc;
  logic        mret_taken;
  logic        redirect_valid;
  logic [31:0] redirect_pc;
  logic [31:0] csr_rdata;
  logic        hazard_load_use;
  logic        hazard_fwd_rs1_ex;
  logic        hazard_fwd_rs1_wb;
  logic        hazard_fwd_rs2_ex;
  logic        hazard_fwd_rs2_wb;
  logic        unsupported;
  logic        grant_valid;
  logic        default_sel;
  logic        slave_select_err;
  logic        hresetn_seen_q;
  logic        hart_reset_event;

  assign dbg_halted_o = core_debug.halted;
  assign dbg_running_o = core_debug.running;

  assign irq_src = {
    dma_irq,
    gpio_irq,
    i2c_irq,
    uart_irq,
    wdg_irq,
    1'b0
  };

  // The Debug Module records that the hart has experienced reset after the SoC
  // reset releases. The pulse is synchronous to hclk_i and feeds dmstatus.
  always_ff @(posedge hclk_i or negedge hresetn_i) begin
    if (!hresetn_i) begin
      hresetn_seen_q <= 1'b0;
      hart_reset_event <= 1'b0;
    end else begin
      hart_reset_event <= !hresetn_seen_q;
      hresetn_seen_q <= 1'b1;
    end
  end

  wasp1_core_ahb_bridge u_core_ahb_bridge (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .imem_if(imem_if),
    .dmem_if(dmem_if),
    .haddr_o(core_haddr),
    .htrans_o(core_htrans),
    .hwrite_o(core_hwrite),
    .hsize_o(core_hsize),
    .hburst_o(core_hburst),
    .hprot_o(core_hprot),
    .hmastlock_o(core_hmastlock),
    .hwdata_o(core_hwdata),
    .hrdata_i(core_hrdata),
    .hready_i(core_hready),
    .hresp_i(core_hresp)
  );

  tile u_tile (
    .clk_i(hclk_i),
    .rst_ni(hresetn_i),
    .boot_pc_i(OTP_BASE),
    .timer_irq_i(timer_irq),
    .external_irq_i(external_irq),
    .icache_flush_i(1'b0),
    .icache_invalidate_i(1'b0),
    .dcache_flush_i(1'b0),
    .dcache_invalidate_i(1'b0),
    .commit_valid_o(commit_valid),
    .commit_rd_o(commit_rd),
    .commit_data_o(commit_data),
    .ex_valid_o(ex_valid),
    .ex_pc_o(ex_pc),
    .ex_instr_o(ex_instr),
    .illegal_o(illegal),
    .lsu_fault_o(lsu_fault),
    .trap_valid_o(trap_valid_o),
    .trap_interrupt_o(trap_interrupt),
    .trap_cause_o(trap_cause_o),
    .trap_tval_o(trap_tval),
    .trap_pc_o(trap_pc),
    .mret_taken_o(mret_taken),
    .redirect_valid_o(redirect_valid),
    .redirect_pc_o(redirect_pc),
    .csr_rdata_o(csr_rdata),
    .hazard_load_use_o(hazard_load_use),
    .hazard_fwd_rs1_ex_o(hazard_fwd_rs1_ex),
    .hazard_fwd_rs1_wb_o(hazard_fwd_rs1_wb),
    .hazard_fwd_rs2_ex_o(hazard_fwd_rs2_ex),
    .hazard_fwd_rs2_wb_o(hazard_fwd_rs2_wb),
    .unsupported_o(unsupported),
    .core_debug(core_debug),
    .imem_if(imem_if),
    .dmem_if(dmem_if)
  );

  debug_jtag u_debug_jtag (
    .clk_i              (hclk_i),
    .rst_ni             (hresetn_i),
    .tck_i              (jtag_tck_i),
    .trst_ni            (jtag_trst_ni),
    .tms_i              (jtag_tms_i),
    .tdi_i              (jtag_tdi_i),
    .tdo_o              (jtag_tdo_o),
    .core_debug         (core_debug),
    .hart_reset_event_i (hart_reset_event),
    .dmactive_o         (dbg_dmactive_o),
    .ndmreset_o         (dbg_ndmreset_o),
    .dtm_hardreset_o    (dbg_dtm_hardreset_o)
  );

  ahb_fabric_2m u_ahb_fabric_2m (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .m0_haddr_i(core_haddr),
    .m0_htrans_i(core_htrans),
    .m0_hwrite_i(core_hwrite),
    .m0_hsize_i(core_hsize),
    .m0_hburst_i(core_hburst),
    .m0_hprot_i(core_hprot),
    .m0_hmastlock_i(core_hmastlock),
    .m0_hwdata_i(core_hwdata),
    .m0_hrdata_o(core_hrdata),
    .m0_hready_o(core_hready),
    .m0_hresp_o(core_hresp),
    .m1_haddr_i(dma_m_haddr),
    .m1_htrans_i(dma_m_htrans),
    .m1_hwrite_i(dma_m_hwrite),
    .m1_hsize_i(dma_m_hsize),
    .m1_hburst_i(dma_m_hburst),
    .m1_hprot_i(dma_m_hprot),
    .m1_hmastlock_i(dma_m_hmastlock),
    .m1_hwdata_i(dma_m_hwdata),
    .m1_hrdata_o(dma_m_hrdata),
    .m1_hready_o(dma_m_hready),
    .m1_hresp_o(dma_m_hresp),
    .slave_hsel_o(slave_hsel),
    .slave_haddr_o(slave_haddr),
    .slave_htrans_o(slave_htrans),
    .slave_hwrite_o(slave_hwrite),
    .slave_hsize_o(slave_hsize),
    .slave_hburst_o(slave_hburst),
    .slave_hprot_o(slave_hprot),
    .slave_hmastlock_o(slave_hmastlock),
    .slave_hwdata_o(slave_hwdata),
    .slave_hrdata_i(slave_hrdata),
    .slave_hready_i(slave_hready),
    .slave_hresp_i(slave_hresp),
    .grant_valid_o(grant_valid),
    .grant_idx_o(bus_grant_idx_o),
    .default_sel_o(default_sel),
    .slave_select_err_o(slave_select_err)
  );

  ahb_otp #(
    .BASE_ADDR(OTP_BASE),
    .MEM_BYTES(OTP_BYTES)
  ) u_ahb_otp (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .hsel_i(slave_hsel[AHB_SLAVE_OTP]),
    .haddr_i(slave_haddr),
    .htrans_i(slave_htrans),
    .hwrite_i(slave_hwrite),
    .hsize_i(slave_hsize),
    .hwdata_i(slave_hwdata),
    .hrdata_o(slave_hrdata[AHB_SLAVE_OTP]),
    .hready_o(slave_hready[AHB_SLAVE_OTP]),
    .hresp_o(slave_hresp[AHB_SLAVE_OTP])
  );

  ahb_sram #(
    .BASE_ADDR(ISRAM_BASE),
    .MEM_BYTES(ISRAM_BYTES)
  ) u_ahb_isram (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .hsel_i(slave_hsel[AHB_SLAVE_ISRAM]),
    .haddr_i(slave_haddr),
    .htrans_i(slave_htrans),
    .hwrite_i(slave_hwrite),
    .hsize_i(slave_hsize),
    .hwdata_i(slave_hwdata),
    .hrdata_o(slave_hrdata[AHB_SLAVE_ISRAM]),
    .hready_o(slave_hready[AHB_SLAVE_ISRAM]),
    .hresp_o(slave_hresp[AHB_SLAVE_ISRAM])
  );

  ahb_sram #(
    .BASE_ADDR(DSRAM_BASE),
    .MEM_BYTES(DSRAM_BYTES)
  ) u_ahb_dsram (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .hsel_i(slave_hsel[AHB_SLAVE_DSRAM]),
    .haddr_i(slave_haddr),
    .htrans_i(slave_htrans),
    .hwrite_i(slave_hwrite),
    .hsize_i(slave_hsize),
    .hwdata_i(slave_hwdata),
    .hrdata_o(slave_hrdata[AHB_SLAVE_DSRAM]),
    .hready_o(slave_hready[AHB_SLAVE_DSRAM]),
    .hresp_o(slave_hresp[AHB_SLAVE_DSRAM])
  );

  ahb_dma u_ahb_dma (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .s_hsel_i(slave_hsel[AHB_SLAVE_DMA]),
    .s_haddr_i(slave_haddr),
    .s_htrans_i(slave_htrans),
    .s_hwrite_i(slave_hwrite),
    .s_hsize_i(slave_hsize),
    .s_hwdata_i(slave_hwdata),
    .s_hrdata_o(slave_hrdata[AHB_SLAVE_DMA]),
    .s_hready_o(slave_hready[AHB_SLAVE_DMA]),
    .s_hresp_o(slave_hresp[AHB_SLAVE_DMA]),
    .m_haddr_o(dma_m_haddr),
    .m_htrans_o(dma_m_htrans),
    .m_hwrite_o(dma_m_hwrite),
    .m_hsize_o(dma_m_hsize),
    .m_hburst_o(dma_m_hburst),
    .m_hprot_o(dma_m_hprot),
    .m_hmastlock_o(dma_m_hmastlock),
    .m_hwdata_o(dma_m_hwdata),
    .m_hrdata_i(dma_m_hrdata),
    .m_hready_i(dma_m_hready),
    .m_hresp_i(dma_m_hresp),
    .dma_irq_o(dma_irq)
  );

  ahb_wdg u_ahb_wdg (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .hsel_i(slave_hsel[AHB_SLAVE_WDG]),
    .haddr_i(slave_haddr),
    .htrans_i(slave_htrans),
    .hwrite_i(slave_hwrite),
    .hsize_i(slave_hsize),
    .hwdata_i(slave_hwdata),
    .hrdata_o(slave_hrdata[AHB_SLAVE_WDG]),
    .hready_o(slave_hready[AHB_SLAVE_WDG]),
    .hresp_o(slave_hresp[AHB_SLAVE_WDG]),
    .wdg_irq_o(wdg_irq),
    .wdg_reset_req_o(wdg_reset_req_o)
  );

  ahb_timer u_ahb_timer (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .hsel_i(slave_hsel[AHB_SLAVE_TIMER]),
    .haddr_i(slave_haddr),
    .htrans_i(slave_htrans),
    .hwrite_i(slave_hwrite),
    .hsize_i(slave_hsize),
    .hwdata_i(slave_hwdata),
    .hrdata_o(slave_hrdata[AHB_SLAVE_TIMER]),
    .hready_o(slave_hready[AHB_SLAVE_TIMER]),
    .hresp_o(slave_hresp[AHB_SLAVE_TIMER]),
    .timer_irq_o(timer_irq)
  );

  ahb_intc u_ahb_intc (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .hsel_i(slave_hsel[AHB_SLAVE_INTC]),
    .haddr_i(slave_haddr),
    .htrans_i(slave_htrans),
    .hwrite_i(slave_hwrite),
    .hsize_i(slave_hsize),
    .hwdata_i(slave_hwdata),
    .hrdata_o(slave_hrdata[AHB_SLAVE_INTC]),
    .hready_o(slave_hready[AHB_SLAVE_INTC]),
    .hresp_o(slave_hresp[AHB_SLAVE_INTC]),
    .irq_src_i(irq_src),
    .meip_o(external_irq),
    .claim_id_o(intc_claim_id)
  );

  ahb_uart u_ahb_uart (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .hsel_i(slave_hsel[AHB_SLAVE_UART]),
    .haddr_i(slave_haddr),
    .htrans_i(slave_htrans),
    .hwrite_i(slave_hwrite),
    .hsize_i(slave_hsize),
    .hwdata_i(slave_hwdata),
    .hrdata_o(slave_hrdata[AHB_SLAVE_UART]),
    .hready_o(slave_hready[AHB_SLAVE_UART]),
    .hresp_o(slave_hresp[AHB_SLAVE_UART]),
    .uart_rx_i(uart_rx_i),
    .uart_tx_o(uart_tx_o),
    .uart_irq_o(uart_irq)
  );

  ahb_i2c u_ahb_i2c (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .hsel_i(slave_hsel[AHB_SLAVE_I2C]),
    .haddr_i(slave_haddr),
    .htrans_i(slave_htrans),
    .hwrite_i(slave_hwrite),
    .hsize_i(slave_hsize),
    .hwdata_i(slave_hwdata),
    .hrdata_o(slave_hrdata[AHB_SLAVE_I2C]),
    .hready_o(slave_hready[AHB_SLAVE_I2C]),
    .hresp_o(slave_hresp[AHB_SLAVE_I2C]),
    .i2c_scl_i(i2c_scl_i),
    .i2c_sda_i(i2c_sda_i),
    .i2c_scl_o(i2c_scl_o),
    .i2c_scl_oe_o(i2c_scl_oe_o),
    .i2c_sda_o(i2c_sda_o),
    .i2c_sda_oe_o(i2c_sda_oe_o),
    .i2c_irq_o(i2c_irq)
  );

  ahb_gpio #(
    .GPIO_WIDTH(GPIO_WIDTH)
  ) u_ahb_gpio (
    .hclk_i(hclk_i),
    .hresetn_i(hresetn_i),
    .hsel_i(slave_hsel[AHB_SLAVE_GPIO]),
    .haddr_i(slave_haddr),
    .htrans_i(slave_htrans),
    .hwrite_i(slave_hwrite),
    .hsize_i(slave_hsize),
    .hwdata_i(slave_hwdata),
    .hrdata_o(slave_hrdata[AHB_SLAVE_GPIO]),
    .hready_o(slave_hready[AHB_SLAVE_GPIO]),
    .hresp_o(slave_hresp[AHB_SLAVE_GPIO]),
    .gpio_in_i(gpio_in_i),
    .gpio_out_o(gpio_out_o),
    .gpio_oe_o(gpio_oe_o),
    .gpio_irq_o(gpio_irq)
  );

  // Keep intentionally observed-but-unused integration diagnostics visible to
  // lint without changing hardware behavior.
  logic unused_integration_status;
  assign unused_integration_status = grant_valid ^ default_sel ^ slave_select_err ^
                                     (|intc_claim_id) ^ commit_valid ^ (|commit_rd) ^
                                     (|commit_data) ^ ex_valid ^ (|ex_pc) ^
                                     (|ex_instr) ^ illegal ^ lsu_fault ^
                                     trap_interrupt ^ (|trap_tval) ^ (|trap_pc) ^
                                     mret_taken ^ redirect_valid ^ (|redirect_pc) ^
                                     (|csr_rdata) ^ hazard_load_use ^
                                     hazard_fwd_rs1_ex ^ hazard_fwd_rs1_wb ^
                                     hazard_fwd_rs2_ex ^ hazard_fwd_rs2_wb ^
                                     unsupported ^ slave_hburst[0] ^ slave_hprot[0] ^
                                     slave_hmastlock;
endmodule
