+incdir+../common/rtl
+incdir+../debug/rtl
../common/rtl/wasp1_pkg.sv
../common/rtl/mem_req_rsp_if.sv
../common/rtl/debug_if.sv
../common/rtl/simple_fifo.sv
../core/rtl/core_types_pkg.sv
../frontend/rtl/frontend_pc.sv
../frontend/rtl/frontend_fetch.sv
../frontend/rtl/frontend_ibuf.sv
../frontend/rtl/frontend.sv
../icache/rtl/icache_tag.sv
../icache/rtl/icache_data.sv
../icache/rtl/icache_refill.sv
../icache/rtl/icache_ctrl.sv
../icache/rtl/icache.sv
../core/rtl/core_alu.sv
../core/rtl/core_regfile.sv
../core/rtl/core_decode.sv
../core/rtl/core_branch.sv
../core/rtl/core_csr.sv
../core/rtl/core_lsu.sv
../core/rtl/core_trap.sv
../core/rtl/core_hazard.sv
../core/rtl/core_wb.sv
../core/rtl/core_debug_ctrl.sv
../core/rtl/core_pipe.sv
../core/rtl/core_int_datapath.sv
../core/rtl/core.sv
../dcache/rtl/dcache_tag.sv
../dcache/rtl/dcache_data.sv
../dcache/rtl/dcache_refill.sv
../dcache/rtl/dcache_store.sv
../dcache/rtl/dcache_ctrl.sv
../dcache/rtl/dcache.sv
../tile/rtl/tile.sv
../bus/rtl/ahb_arbiter_2m.sv
../bus/rtl/ahb_decoder.sv
../bus/rtl/ahb_default_slave.sv
../bus/rtl/ahb_slave_mux.sv
../bus/rtl/ahb_fabric_2m.sv
../sram/rtl/ahb_sram.sv
../otp/rtl/ahb_otp.sv
../dma/rtl/ahb_dma.sv
../wdg/rtl/ahb_wdg.sv
../timer/rtl/ahb_timer.sv
../intc/rtl/ahb_intc.sv
../uart/rtl/uart_baud.sv
../uart/rtl/uart_tx.sv
../uart/rtl/uart_rx.sv
../uart/rtl/ahb_uart.sv
../i2c/rtl/ahb_i2c.sv
../gpio/rtl/ahb_gpio.sv
../debug/rtl/debug_dmi_pkg.sv
../debug/rtl/debug_dmi_if.sv
../debug/rtl/debug_dmi_regs.sv
../debug/rtl/debug_halt_ctrl.sv
../debug/rtl/debug_abstract_cmd.sv
../debug/rtl/debug_reg_access.sv
../debug/rtl/debug.sv
../debug/rtl/debug_jtag_dtm.sv
../debug/rtl/debug_jtag.sv
rtl/wasp1_core_ahb_bridge.sv
rtl/wasp1.sv
